apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wj0pb89fj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wj0pb89fj-go 
  name: wj0pb89fj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wj0pb89fj-go 
