apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wj0pb89fj-go 
  janus-idp.io/tekton: wj0pb89fj-go
  backstage.io/kubernetes-id: wj0pb89fj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wj0pb89fj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml